Fixes #2898: Build CI on more realistic combinations (and faster)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,10 +9,10 @@ name: CI
 
 on:
   push:
-    branches: ['main']
-    tags: [v*]
+    branches: [ 'main' ]
+    tags: [ v* ]
   pull_request:
-    branches: ['**']
+    branches: [ '**' ]
 
 permissions:
   contents: read
@@ -26,10 +26,65 @@ jobs:
     runs-on: ubuntu-latest
     if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
 
+    # All build steps
+    # SINGLE-MATRIX-JOB means that the step does not need to be executed on every job in the matrix
+    steps:
+
+      - name: 1. Check out code
+        uses: actions/checkout@v3 # https://github.com/actions/checkout
+        with:
+          fetch-depth: '0' # https://github.com/shipkit/shipkit-changelog#fetch-depth-on-ci
+
+      - name: 2. Set up Java 11
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'zulu'
+          java-version: 11
+
+      - name: 3. Validate Gradle wrapper
+        uses: gradle/wrapper-validation-action@v1.0.6 # https://github.com/gradle/wrapper-validation-action
+
+      - name: 4. Build and check reproducibility of artifacts (single job only)
+        run: ./check_reproducibility.sh
+
+      - name: 5. Spotless check (single job only). Run './gradlew spotlessApply' locally if this job fails.
+        run: ./gradlew spotlessCheck
+
+      - name: 6. Build on Java 11
+        run: ./gradlew build idea --scan
+
+      - name: 7. Upload build artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: build
+          path: build
+
+      - name: 8. Upload coverage report
+        run: |
+          ./gradlew coverageReport -s --scan && cp build/reports/jacoco/mockitoCoverage/mockitoCoverage.xml jacoco.xml
+          curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
+
+          curl -Os https://uploader.codecov.io/latest/linux/codecov
+          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
+          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
+
+          gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
+          shasum -a 256 -c codecov.SHA256SUM
+
+          chmod +x codecov
+          ./codecov
+  #
+  # Main test job
+  #
+  test:
+    needs: build
+    runs-on: ubuntu-latest
+    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
+
     # Definition of the build matrix
     strategy:
       matrix:
-        java: [11, 17]
+        java: [ 8, 9, 10, 12, 13, 14, 15, 16, 17 ]
         entry:
           - { mock-maker: 'mock-maker-default', member-accessor: 'member-accessor-default' }
           - { mock-maker: 'mock-maker-inline', member-accessor: 'member-accessor-module' }
@@ -37,53 +92,42 @@ jobs:
           - { mock-maker: 'mock-maker-subclass', member-accessor: 'member-accessor-reflection' }
           - { mock-maker: 'mock-maker-inline', member-accessor: 'member-accessor-reflection' }
 
+
     # All build steps
     # SINGLE-MATRIX-JOB means that the step does not need to be executed on every job in the matrix
     steps:
+      - name: 1. Download build artifacts build on Java 11
+        uses: actions/download-artifact@v3
+        with:
+          name: build
+          path: build
 
-    - name: 1. Check out code
-      uses: actions/checkout@v3 # https://github.com/actions/checkout
-      with:
-        fetch-depth: '0' # https://github.com/shipkit/shipkit-changelog#fetch-depth-on-ci
+      - name: 2. Set up Java ${{ matrix.java }}
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'zulu'
+          java-version: ${{ matrix.java }}
 
-    - name: 2. Set up Java ${{ matrix.java }}
-      uses: actions/setup-java@v3
-      with:
-        distribution: 'zulu'
-        java-version: ${{ matrix.java }}
+      - name: 6. Test on Java ${{ matrix.java }} with ${{ matrix.entry.mock-maker }} and ${{ matrix.entry.member-accessor }}
+        run: ./gradle test
+        env:
+          MOCK_MAKER: ${{ matrix.entry.mock-maker }}
+          MEMBER_ACCESSOR: ${{ matrix.entry.member-accessor }}
 
-    - name: 3. Validate Gradle wrapper
-      if: matrix.java == 11 && matrix.entry.mock-maker == 'mock-maker-default' # SINGLE-MATRIX-JOB
-      uses: gradle/wrapper-validation-action@v1.0.6 # https://github.com/gradle/wrapper-validation-action
+      - name: 8. Upload coverage report
+        run: |
+          ./gradlew coverageReport -s --scan && cp build/reports/jacoco/mockitoCoverage/mockitoCoverage.xml jacoco.xml
+          curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
 
-    - name: 4. Build and check reproducibility of artifacts (single job only)
-      if: matrix.java == 11 && matrix.entry.mock-maker == 'mock-maker-default' # SINGLE-MATRIX-JOB
-      run: ./check_reproducibility.sh
+          curl -Os https://uploader.codecov.io/latest/linux/codecov
+          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
+          curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
 
-    - name: 5. Spotless check (single job only). Run './gradlew spotlessApply' locally if this job fails.
-      if: matrix.java == 11 && matrix.entry.mock-maker == 'mock-maker-default' # SINGLE-MATRIX-JOB
-      run: ./gradlew spotlessCheck
+          gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
+          shasum -a 256 -c codecov.SHA256SUM
 
-    - name: 6. Build on Java ${{ matrix.java }} with ${{ matrix.entry.mock-maker }} and ${{ matrix.entry.member-accessor }}
-      run: ./gradlew build idea --scan
-      env:
-        MOCK_MAKER: ${{ matrix.entry.mock-maker }}
-        MEMBER_ACCESSOR: ${{ matrix.entry.member-accessor }}
-
-    - name: 7. Upload coverage report
-      run: |
-        ./gradlew coverageReport -s --scan && cp build/reports/jacoco/mockitoCoverage/mockitoCoverage.xml jacoco.xml
-        curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
-
-        curl -Os https://uploader.codecov.io/latest/linux/codecov
-        curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
-        curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
-
-        gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
-        shasum -a 256 -c codecov.SHA256SUM
-
-        chmod +x codecov
-        ./codecov
+          chmod +x codecov
+          ./codecov
 
   #
   # Android build job
@@ -101,70 +145,70 @@ jobs:
 
     # All build steps
     steps:
-    - name: 1. Check out code
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: '0' # https://github.com/shipkit/shipkit-changelog#fetch-depth-on-ci
+      - name: 1. Check out code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: '0' # https://github.com/shipkit/shipkit-changelog#fetch-depth-on-ci
 
-    - name: 2. Set up Java 11
-      uses: actions/setup-java@v3
-      with:
-        distribution: 'zulu'
-        java-version: 11
+      - name: 2. Set up Java 11
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'zulu'
+          java-version: 11
 
-    - name: 3. Run Android tests on Android API level ${{ matrix.android-api }}
-      uses: reactivecircus/android-emulator-runner@v2
-      with:
-        arch: x86_64
-        api-level: ${{ matrix.android-api }}
-        # Workaround for https://issuetracker.google.com/issues/267458959
-        target: ${{ matrix.android-api >= 32 && 'google_apis' || 'default' }}
-        # Workaround for https://github.com/ReactiveCircus/android-emulator-runner/issues/160, but newer version.
-        emulator-build: 9322596 # 31.3.14.0 got it via `emulator -version`
-        # Override default "-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim"
-        # See emulator manual for reference: https://developer.android.com/studio/run/emulator-commandline
-        emulator-options: >
-          -no-window
-          -gpu swiftshader_indirect
-          -no-snapshot
-          -noaudio
-          -no-boot-anim
-          -camera-back none
-          -camera-front none
-        # See logcat manual for reference: https://developer.android.com/studio/command-line/logcat
-        script: |
-          # Capture logcat output from "Launch Emulator" to a file.
-          adb logcat -d > emulator-startup.log
-          # Shorten the logcat output, by truncating at this point, the relevant part is yet to come.
-          # Best effort, could fail with "failed to clear the 'main' log",
-          # because something is locking logcat, so try a few times, and ignore errors each time.
-          adb logcat --clear || true
-          adb logcat --clear || true
-          adb logcat --clear || true
-          # Capture full logcat output to a file.
-          adb logcat > emulator.log & echo $! > logcat_file.pid
-          # Output instrumentation test logs to the GitHub Actions output.
-          adb logcat "*:S MonitoringInstr:V AndroidJUnitRunner:V TestRequestBuilder:V TestExecutor:V TestRunner:V" --format=color & echo $! > logcat_console.pid
+      - name: 3. Run Android tests on Android API level ${{ matrix.android-api }}
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          arch: x86_64
+          api-level: ${{ matrix.android-api }}
+          # Workaround for https://issuetracker.google.com/issues/267458959
+          target: ${{ matrix.android-api >= 32 && 'google_apis' || 'default' }}
+          # Workaround for https://github.com/ReactiveCircus/android-emulator-runner/issues/160, but newer version.
+          emulator-build: 9322596 # 31.3.14.0 got it via `emulator -version`
+          # Override default "-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim"
+          # See emulator manual for reference: https://developer.android.com/studio/run/emulator-commandline
+          emulator-options: >
+            -no-window
+            -gpu swiftshader_indirect
+            -no-snapshot
+            -noaudio
+            -no-boot-anim
+            -camera-back none
+            -camera-front none
+          # See logcat manual for reference: https://developer.android.com/studio/command-line/logcat
+          script: |
+            # Capture logcat output from "Launch Emulator" to a file.
+            adb logcat -d > emulator-startup.log
+            # Shorten the logcat output, by truncating at this point, the relevant part is yet to come.
+            # Best effort, could fail with "failed to clear the 'main' log",
+            # because something is locking logcat, so try a few times, and ignore errors each time.
+            adb logcat --clear || true
+            adb logcat --clear || true
+            adb logcat --clear || true
+            # Capture full logcat output to a file.
+            adb logcat > emulator.log & echo $! > logcat_file.pid
+            # Output instrumentation test logs to the GitHub Actions output.
+            adb logcat "*:S MonitoringInstr:V AndroidJUnitRunner:V TestRequestBuilder:V TestExecutor:V TestRunner:V" --format=color & echo $! > logcat_console.pid
 
-          echo 0 > gradle.exit # Set a default exit code.
-          # Run the actual tests (suppress build failures by saving the exit code).
-          ./gradlew :androidTest:connectedCheck --no-daemon --no-build-cache || echo $? > gradle.exit
+            echo 0 > gradle.exit # Set a default exit code.
+            # Run the actual tests (suppress build failures by saving the exit code).
+            ./gradlew :androidTest:connectedCheck --no-daemon --no-build-cache || echo $? > gradle.exit
 
-          # Stop capturing logcat output.
-          kill $(cat logcat_file.pid)    || echo "::warning file=.github/workflows/ci.yml::Logcat process $(cat logcat_file.pid) didn't exist."
-          kill $(cat logcat_console.pid) || echo "::warning file=.github/workflows/ci.yml::Logcat process $(cat logcat_console.pid) didn't exist."
-          # Make sure the step fails if the tests failed.
-          exit $(cat gradle.exit)
+            # Stop capturing logcat output.
+            kill $(cat logcat_file.pid)    || echo "::warning file=.github/workflows/ci.yml::Logcat process $(cat logcat_file.pid) didn't exist."
+            kill $(cat logcat_console.pid) || echo "::warning file=.github/workflows/ci.yml::Logcat process $(cat logcat_console.pid) didn't exist."
+            # Make sure the step fails if the tests failed.
+            exit $(cat gradle.exit)
 
-    - name: 4. Upload artifact "androidTest-results-${{ matrix.android-api }}"
-      if: success() || failure()
-      uses: actions/upload-artifact@v3
-      with:
-        name: androidTest-results-${{ matrix.android-api }}
-        path: |
-          ${{ github.workspace }}/subprojects/androidTest/build/reports/androidTests/connected/**
-          ${{ github.workspace }}/emulator.log
-          ${{ github.workspace }}/emulator-startup.log
+      - name: 4. Upload artifact "androidTest-results-${{ matrix.android-api }}"
+        if: success() || failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: androidTest-results-${{ matrix.android-api }}
+          path: |
+            ${{ github.workspace }}/subprojects/androidTest/build/reports/androidTests/connected/**
+            ${{ github.workspace }}/emulator.log
+            ${{ github.workspace }}/emulator-startup.log
 
   #
   # Release job, only for pushes to the main development branch
@@ -173,12 +217,12 @@ jobs:
     permissions:
       contents: write
     runs-on: ubuntu-latest
-    needs: [build] # build job must pass before we can release
+    needs: [ build ] # build job must pass before we can release
 
     if: github.event_name == 'push'
-        && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
-        && github.repository == 'mockito/mockito'
-        && !contains(toJSON(github.event.commits.*.message), '[skip release]')
+      && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
+      && github.repository == 'mockito/mockito'
+      && !contains(toJSON(github.event.commits.*.message), '[skip release]')
 
     steps:
 
